FROM ghcr.io/zcaudate-xyz/infra-foundation-clean:main
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

RUN apt-get update && apt-get -y install nano tmux

# Tmux conf
ADD ./infra-dev/infra/.tmux.conf /root/.tmux.conf

ADD foundation-base /tmp/foundation-base
RUN cd /tmp/foundation-base && lein install

ADD foundation-embed /tmp/foundation-embed
RUN cd /tmp/foundation-embed && lein install

ADD foundation-fx /tmp/foundation-fx
RUN cd /tmp/foundation-fx && lein install

ADD foundation-web /tmp/foundation-web
RUN cd /tmp/foundation-web && lein install

# Hosts
ADD ./infra-dev/infra/hosts /etc/hosts

# Entrypoint
ADD ./infra-dev/infra/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]