FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

ARG ARCH

RUN if [ "$ARCH" = "amd64" ]; then \
        echo "Running on amd64 architecture"; \
    elif [ "$ARCH" = "arm64" ]; then \
        echo "Running on arm64 architecture"; \
    else \
        echo "Unknown architecture"; \
    fi

# Conditional logic based on the architecture argument
#RUN if [ "$ARCH" = "amd64" ]; then \
#        wget https://dl.min.io/server/minio/release/linux-amd64/minio_20241218131544.0.0_amd64.deb -O minio.deb && sudo dpkg -i minio.deb \
#    elif [ "$ARCH" = "arm64" ]; then \
#        wget https://dl.min.io/server/minio/release/linux-arm64/minio_20241218131544.0.0_arm64.deb -O minio.deb && sudo dpkg -i minio.deb \
#    else \
#        echo "Unknown architecture"; \
#    fi
