name: Build Dev Infra

on: 
    repository_dispatch:
      types: [infra-changed, code-changed]
    workflow_dispatch:

jobs:
  
  build-container-arm64:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        downstream: ['statstrade-dev/ci']
      
    steps:      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: foundation-ci
          
      - name: Checkout base repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout embed repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout fx repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout web repository
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-web
          path: foundation-web
          token: ${{ secrets.GH_TOKEN }}
          
      - name: List Directory
        run: ls -al        
        
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate-xyz/infra-foundation-dev

      - name: Build and push Docker infra images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./foundation-ci/infra/Dockerfile_foundation_dev
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
