name: Make Xtbench Packages Public

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-xtbench-ci.yml'
      - 'infra/Dockerfile_foundation_xtbench_ci'
      - 'Makefile'
      - 'README.md'
  repository_dispatch:
    types: [infra-clean-main-changed]
  workflow_dispatch:

jobs:
  make-xtbench-public:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        lang: [dart, js, julia, lua, r, ruby]

    steps:
      - name: Make xtbench package public - ${{ matrix.lang }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >
          gh api
          --method PATCH
          -H "Accept: application/vnd.github+json"
          /orgs/zcaudate-xyz/packages/container/infra-foundation-xtbench-${{ matrix.lang }}/visibility
          -f visibility=public
