name: Build Clean Infra

on: [workflow_dispatch]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate-xyz/infra-foundation-clean
      
      - name: Build and push Docker infra images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/Dockerfile_foundation_clean
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Notify Downstream
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/infra-foundation
          event-type: infra-changed
          
      - name: Notify foundation-base
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/foundation-base
          event-type: infra-changed
          
      - name: Notify foundation-embed
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/foundation-embed
          event-type: infra-changed
          
      - name: Notify foundation-fx
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/foundation-fx
          event-type: infra-changed
          
      - name: Notify foundation-web
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/foundation-web
          event-type: infra-changed
