name: Build Clean Infra

on: [workflow_dispatch]

jobs:
    
  build:
    runs-on: ubuntu-latest
      
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate-xyz/infra-foundation-clean
      
      - name: Build and push Docker infra images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/Dockerfile_foundation_clean
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  build-ci:
    runs-on: ubuntu-latest
      
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Build and push Docker infra images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/Dockerfile_foundation_clean
          push: true
          tags: ghcr.io/zcaudate-xyz/infra-foundation-clean:ci
          labels: ${{ steps.meta.outputs.labels }}

  notify-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify downstream
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate-xyz/infra-dev
          event-type: infra-clean-main-changed
          client-payload: '{"repo": "${{ github.repository.id }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "comment": "${{ github.payload.comment }}"}'
          
  notify-tests:
    needs: build-ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        downstream:
            - 'zcaudate-xyz/foundation-base'
            - 'zcaudate-xyz/foundation-embed'
            - 'zcaudate-xyz/foundation-fx'
            - 'zcaudate-xyz/foundation-web'
            - 'zcaudate-xyz/infra-dev

    steps:
      - name: Notify downstream
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ matrix.downstream }}
          event-type: infra-clean-ci-changed
          client-payload: '{"repo": "${{ github.repository.id }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "comment": "${{ github.payload.comment }}"}'
